### ISSUE TITLE
FieldDoesNotExist Import No Longer Valid

### ISSUE THREAD

**Issue by chris-umed** [paulocheque/django-dynamic-fixture#135]
In Django 3.1 **_FieldDoesNotExist_** is no longer available via  django.db.models.fields

It has to be imported from the source file:
`from django.core.exceptions import FieldDoesNotExist`

This is the error I get:
from django_dynamic_fixture.django_helper import get_related_model, \
  vi +12 .local/share/virtualenvs/tern-KsBtVxbD/lib/python3.7/site-packages/django_dynamic_fixture/django_helper.py  # <module>
    from django.db.models.fields import NOT_PROVIDED, AutoField, FieldDoesNotExist
ImportError: cannot import name 'FieldDoesNotExist' from 'django.db.models.fields'

**Comment by chris-umed** [comment]
Just seen there is a PR for this:
https://github.com/paulocheque/django-dynamic-fixture/pull/134

It would be hugely appreciated if this could be reviewed and merged.

**Comment by JanMalte** [comment]
https://docs.djangoproject.com/en/3.1/releases/3.1/#id1
