### ISSUE TITLE
typing wrong for `G` function when `n` > 1

### ISSUE THREAD

**Issue by sasacocic** [paulocheque/django-dynamic-fixture#163]
When you create models using `G` and you use `n` and it's greater than like in the example below the type information is incorrect. I would expect to get back `list[Req]` not `Req`. I've attached an image below to show this in vscode.

```
from my_djangoapp.models import Req
req = ddf.G(Req, 10)  
```

<img width="228" alt="Screenshot 2024-07-25 at 6 29 04 PM" src="https://github.com/user-attachments/assets/4d5fe8a9-e34b-453c-b75a-1e277d5fc378">

I'd be glad to put up a PR to fix this as it's a pretty easy fix. 

A potential solution would be to just change the type definition although there might be a way to get better ergonomics than that

```python
def get(model: typing.Type[INSTANCE_TYPE], n: int=1, ddf_lesson=None, **kwargs) -> INSTANCE_TYPE | list[INSTANCE_TYPE]:
```

**Comment by paulocheque** [comment]
A PR would be good!

**Comment by sasacocic** [comment]
@paulocheque I put up a PR: https://github.com/paulocheque/django-dynamic-fixture/pull/164/files
