### ISSUE TITLE
Set max number of instances per model_class?

### ISSUE THREAD

**Issue by vishen** [paulocheque/django-dynamic-fixture#33]
I need the ability to set the maximum number of instances per model_class, is there a way to do this already? 

The the django project I'm using this for is large and complex with lots of relationships every where and I cannot find an easy way to minimise the creating of many instances per model class.

**Comment by paulocheque** [comment]
I had an idea now.
You can use the `teach` method (old `shelve/use_library`) to use always the same model instance.
In this way, DDF won't create a new instance.

For example:

In `conftest.py`
```
from ddf import teach, G

limited_instance = G(MyLimitedModel)
teach(MyModel, my_fk_I_want_to_limit_creation=limited_instance)
```

Then, in your tests:

```
G(MyModel)
```

it won't create its FKs...
