### ISSUE TITLE
Can we change persist_dependencies to False by default on N?

### ISSUE THREAD

**Issue by wesleykendall** [paulocheque/django-dynamic-fixture#52]
According to https://github.com/paulocheque/django-dynamic-fixture/blob/master/django_dynamic_fixture/__init__.py#L71 and the docs, persist_dependencies is True by default for the N function. Almost 100% of time in our code we have to type persist_dependencies=False, and it's cumbersome to have to manually review code and ensure people aren't accidentally hitting the DB when they instantiate in-memory models.

My question - can this default behavior be changed? If it's too backwards breaking, can I add an M function that is N with persist_dependencies=False?

**Comment by paulocheque** [comment]
Well, I changed the default value for the next DDF version 3, which will have some big changes and incompatibilities with older versions.

https://github.com/paulocheque/django-dynamic-fixture/pull/108

Thanks @wesleykendall @micahhausler

**Comment by wesleykendall** [comment]
@paulocheque thanks so much for this change! Loving version 3!
