### ISSUE TITLE
DDFImproperlyConfigured DDF_DEFAULT_DATA_FIXTURE 

### ISSUE THREAD

**Issue by learner010** [paulocheque/django-dynamic-fixture#55]
My settings file is at `project_root/settings/client/dev.py` and the fixture file is at `project_root/libs/fixtures.py`'

My DDF configuration is given below.
`DDF_DEFAULT_DATA_FIXTURE = 'libs.fixtures.ASequentialDataFixture'`

During test I get following error.
`ERROR: Failure: DDFImproperlyConfigured (DDF_DEFAULT_DATA_FIXTURE (libs.fixtures.ASequentialDataFixture) must be 'sequential', 'static_sequential', 'global_sequential', 'random' or 'path.to.CustomDataFixtureClass'.)`

**Comment by paulocheque** [comment]
I believe this may be a problem related to the path you are using. Check the code DDF use to load the module.

            # path.to.CustomDataFixtureClass
            mod_name, obj_name = get_mod_func(settings.DDF_DEFAULT_DATA_FIXTURE)
            module = import_module(mod_name)
            custom_data_fixture = getattr(module, obj_name)
            DDF_DEFAULT_DATA_FIXTURE = custom_data_fixture()

**Comment by paulocheque** [comment]
Hey @learner010  Any new on this?

I will close this issue for now. It appears to be a PYTHON_PATH problem.
