### ISSUE TITLE
DDF_VALIDATE_ARGS should default to DEBUG

### ISSUE THREAD

**Issue by voidus** [paulocheque/django-dynamic-fixture#57]
Hi,

I just activated DDF_VALIDATE_ARGS in one of my projects and immediately found some bugs. It should probably default to whatever value DEBUG is set to, so that problems can be detected as early as possible.

The code says that the current default is False for compatibility reasons, but maybe it could be changed it in the next major version?

**Comment by paulocheque** [comment]
Thanks for the feedback.

I agree with you, but I believe this may generate a very strong headache to the DDF users. I will keep this issue opened to see if more people has more arguments to help us take the best decision.

**Comment by paulocheque** [comment]
@voidus Since we don't get more feedbacks, I completely removed this settings and now DDF will always validate the args: https://github.com/paulocheque/django-dynamic-fixture/pull/107

It is good to simplify things! Thanks a lot!
