### ISSUE TITLE
No support for uuid fields in django 1.8

### ISSUE THREAD

**Issue by czartur** [paulocheque/django-dynamic-fixture#63]
Like in the title,

Trying to `G(ModelName)` with uuid field results in 

```
    raise(UnsupportedFieldError(get_unique_field_name(field)))
UnsupportedFieldError: apps.testapp.models.SomeModel.uuid_field
```

Steps to reproduce: 
1) create a model (eg ``SomeModel``) with ``models.UUIDField`` (eg ``uuid_field``)
2) open `./manage.py shell`
3) do `G(SomeModel)`

Thanks,

**Comment by paulocheque** [comment]
Thanks for reporting. This is a new field.

For now, you can try the `DDF_FIELD_FIXTURES` config: http://ddf.codeart.io/en/latest/data_fixtures.html#custom-field-fixture

**Comment by paulocheque** [comment]
Added support in 1.8.4 version. Thanks for reporting. Best,
