### ISSUE TITLE
Set DDF_IGNORE_FIELDS or ignore_fields argument using wild cards

### ISSUE THREAD

**Issue by rpalacios** [paulocheque/django-dynamic-fixture#67]
Hi.

It would be nice to set `DDF_IGNORE_FIELDS` or `ignore_fields` argument using wild cards.

You could want to ignore a set of fields in one or more models.

By example, when I start using this app on my unit tests, I always get `AttributeError` on polymorphic models. This exception is documented on [django-polymorphic documentation](https://github.com/chrisglass/django_polymorphic/blob/master/docs/admin.rst#polymorphic-inlines). 

To workaorund this, I had to set all fields that ends with "_ptr" to be ignored.

It would be nice to be able to set `DDF_IGNORE_FIELDS = ['*_ptr']`.

Just one suggestion.

Best regards,
Roger

**Comment by paulocheque** [comment]
Excellent suggestion, thanks!

If you are able to create a Pull Request for that, I will be happy to merge it.

**Comment by jmurty** [comment]
FYI this feature is now merged into master from https://github.com/paulocheque/django-dynamic-fixture/pull/85

@paulocheque You may want to mark this ticket as fixed now, or once the merged change is released?

**Comment by paulocheque** [comment]
Thanks!
