### ISSUE TITLE
Deprecation warnings with django 1.8

### ISSUE THREAD

**Issue by cailloumajor** [paulocheque/django-dynamic-fixture#68]
The old and undocumented Model._meta API will be removed in django 1.10. The Model._meta.get_field_by_name(name) method fires a DeprecationWarning since django 1.8.
Django documentation recommends to use new Model._meta.get_field(name) :
https://docs.djangoproject.com/en/1.8/ref/models/meta/#migrating-from-the-old-api

**Comment by cailloumajor** [comment]
Fix is proposed in PR #69

**Comment by paulocheque** [comment]
Amazing!
