### ISSUE TITLE
Please release a new version containing Django 1.9 support

### ISSUE THREAD

**Issue by gregmuellegger** [paulocheque/django-dynamic-fixture#77]
Hi, django-dynamic-fixture has support for Django 1.9 since the merge of #74.

But there is no PyPI release yet, I would love to see a new official support so we can finally use this package in a Django 1.9 project.

Is there any chance there will be a new release in the next weeks?

**Comment by paulocheque** [comment]
Released! Thanks a lot for the PR and sorry for the delay!
