### ISSUE TITLE
GEOS "Point" expects (longitude, latitude)

### ISSUE THREAD

**Issue by michaellea** [paulocheque/django-dynamic-fixture#78]
GeoDjango's "Point" class expects the constructor arguments to be (longitude, latitude) rather than the more traditional (latitude, longitude). Inverting them results in some unexpected behaviour & validation errors.

Fix is likely just to switch the arguments in fixture_algorithms/default_fixture.py:

```
class GeoDjangoDataFixture(object):
    def create_point(self, x=None, y=None):
        # latitude: [-90,90], longitude: [-180,180]
        latitude = x or random.randint(-90, 90)
        longitude = y or random.randint(-180, 180)
        return Point(longitude, latitude)
```

**Comment by serge-gaia** [comment]
Agree, we can't use any geometry operations with this inversion of angles.

**Comment by paulocheque** [comment]
Thanks for the report!

**Comment by paulocheque** [comment]
Added in 1.9.4.

**Comment by serge-gaia** [comment]
:+1:
