### ISSUE TITLE
UnsupportedFieldError: PointField [geoDjango]

### ISSUE THREAD

**Issue by zvictor** [paulocheque/django-dynamic-fixture#8]
Hi,

I realized that DDF has no compatibility with `geodjango`, more specifically with `django.contrib.gis.db.models.fields.PointField`.
I am interested in implement it, but I don't know how to start. How can we deal with `geodjango` requirement, and how am I supposed to test the implementation? Any ideas how can we do it?

**Comment by paulocheque** [comment]
Added support in 1.8.4 version. Thanks for reporting. Best,
