### ISSUE TITLE
`settings` module has a common name that is likely to conflict with other packages.

### ISSUE THREAD

**Issue by mrmachine** [paulocheque/django-dynamic-fixture#81]
My project also has a settings.py, but DDF's is found first when I have installed DDF as editable with `pip install -e ...`

Consider moving this module inside the `django_dynamic_fixture` package to ensure it doesn't conflict with any other packages?

(and I will have to consider moving settings.py in my project, too)

**Comment by paulocheque** [comment]
Just for curiosity, why you are installing it as editable?

**Comment by mrmachine** [comment]
1) because we had to edit it sometimes to work around an incompatibility with django-polymorphic
2) because `pip install -r requirements.txt` will re-download and install a plain HTTP URL every single time, while an editable VCS install will only be updated
3) because when using `pip-tools` to work-around `pip`'s rudimentary "first found wins" nested dependency version conflict resolution, you *must* use editable installs instead of URLs (or otherwise we must use a packaged version from PyPI).

But regardless, installing a top level module named `settings` is likely to conflict with someone's project when they try to use DDF. This is no longer fresh in my memory, so I'm not sure if this is *only* a problem with editable installs?

**Comment by paulocheque** [comment]
Fixed: https://github.com/paulocheque/django-dynamic-fixture/pull/105

Thanks again for the feedback and suggestion.
