### ISSUE TITLE
E   NameError: global name 'instance' is not defined

### ISSUE THREAD

**Issue by saxix** [paulocheque/django-dynamic-fixture#82]
the error is produced in [ddf.py:380](https://github.com/paulocheque/django-dynamic-fixture/blob/master/django_dynamic_fixture/ddf.py#L380)

`getattr(instance, field.name).save(django_file.name, django_file, save=False)`

should be

`getattr(__instance, __field.name).save(django_file.name, django_file, save=False)`

**Comment by paulocheque** [comment]
nice!
