### ISSUE TITLE
UnsupportedFieldError on django.contrib.postgres.fields.array.ArrayField

### ISSUE THREAD

**Issue by firehawk895** [paulocheque/django-dynamic-fixture#84]
Shouldn't PostgreSQL fields supported out of the box? 
PS: thanks for the great library :)

**Comment by paulocheque** [comment]
Thanks for the report. Check this commit, it should be implemented or, at least, useful as a reference for a custom fixture.

**Comment by paulocheque** [comment]
Fixed in 1.9.4.
