### ISSUE TITLE
Support for django.contrib.postgres.fields.JSONField

### ISSUE THREAD

**Issue by variable** [paulocheque/django-dynamic-fixture#95]
Just wondering if this is in the roadmap supporting this field? Currently I am getting

`django_dynamic_fixture.ddf.UnsupportedFieldError: core.models.Invoice.raw_data (django.contrib.postgres.fields.jsonb.JSONField)`

**Comment by paulocheque** [comment]
No roadmap. A PullRequest is welcome though. Or you can create a CustomField locall in your project. Sorry I don't have a better answer for you.

Best!

**Comment by paulocheque** [comment]
Thanks again @variable 
I created a PR to improve this: https://github.com/paulocheque/django-dynamic-fixture/pull/103
