### ISSUE TITLE
Python 3.5: type hints for N() and G() outputs

### ISSUE THREAD

**Issue by Kern3l** [paulocheque/django-dynamic-fixture#96]
Hey,

I know that the support for new Python is not there yet, so I'm not making it a PR. Instead I put here how it can be achieved to have type hints for `N()` and `G()` functions (super useful for using the lib with an IDE that uses type hints).

In `__init__.py`, at the top:
```
import typing

(...)

INSTANCE_TYPE = typing.TypeVar('INSTANCE')
```
Then:
```
def new(model: typing.Type[INSTANCE_TYPE], shelve=False, n=1, persist_dependencies=True, **kwargs) -> INSTANCE_TYPE:
```
```
def get(model: typing.Type[INSTANCE_TYPE], shelve=False, n=1, **kwargs) -> INSTANCE_TYPE:
```

**Comment by paulocheque** [comment]
Thanks @Kern3l  !
I did a hack to handle the Python 2/3 compatibility.
https://github.com/paulocheque/django-dynamic-fixture/pull/102

It is ugly but it works well for a test library.
